export enum PRICE_ORACLES {
  BALANCER = "Balancer",
  UNI = "Uniswap",
}

export enum FALLBACK_STATES {
  HAS_DOMAIN_VERIFIER = "HAS_DOMAIN_VERIFIER",
  HAS_EXTENSIBLE_FALLBACK = "HAS_EXTENSIBLE_FALLBACK",
  HAS_NOTHING = "HAS_NOTHING",
}
