import { createSchema } from "@ponder/core";

export default createSchema((p) => ({
  Order: p.createTable({
    id: p.string(),
    chainId: p.int(),
    blockNumber: p.bigint(),
    blockTimestamp: p.bigint(),
    handler: p.hex(),
    hash: p.hex(),
    salt: p.hex(),
    user: p.string().references("User.id"),
    staticInput: p.hex(),
    decodedSuccess: p.boolean(),
    stopLossParametersId: p
      .string()
      .references("StopLossParameters.id")
      .optional(),
    stopLossParameters: p.one("stopLossParametersId"),
    cowAmmParametersId: p.string().references("CowAmmParameters.id").optional(),
    cowAmmParameters: p.one("cowAmmParametersId"),
  }),
  Token: p.createTable({
    id: p.string(),
    address: p.hex(),
    chainId: p.int(),
    name: p.string(),
    symbol: p.string(),
    decimals: p.int(),
  }),
  User: p.createTable({
    id: p.string(),
    address: p.string(),
    chainId: p.int(),
    orders: p.many("Order.user"),
  }),
  StopLossParameters: p.createTable({
    id: p.string(),
    orderId: p.string().references("Order.id"),
    tokenInId: p.string().references("Token.id"),
    tokenIn: p.one("tokenInId"),
    tokenAmountIn: p.bigint(),
    tokenOutId: p.string().references("Token.id"),
    tokenOut: p.one("tokenOutId"),
    tokenAmountOut: p.bigint(),
    appData: p.hex(),
    to: p.hex(),
    isSellOrder: p.boolean(),
    isPartiallyFillable: p.boolean(),
    validityBucketSeconds: p.bigint(),
    sellTokenPriceOracle: p.hex(),
    buyTokenPriceOracle: p.hex(),
    strike: p.bigint(),
    maxTimeSinceLastOracleUpdate: p.bigint(),
  }),
  CowAmmParameters: p.createTable({
    id: p.string(),
    orderId: p.string().references("Order.id"),
    token0Id: p.string().references("Token.id"),
    token0: p.one("token0Id"),
    token1Id: p.string().references("Token.id"),
    token1: p.one("token1Id"),
    minTradedToken0: p.bigint(),
    priceOracle: p.hex(),
    priceOracleData: p.hex(),
    appData: p.hex(),
  }),
}));
