import { createSchema } from "@ponder/core";

export default createSchema((p) => ({
  Order: p.createTable({
    id: p.string(),
    chainId: p.int(),
    tokenInId: p.string().references("Token.id"),
    tokenIn: p.one("tokenInId"),
    tokenAmountIn: p.bigint(),
    tokenOutId: p.string().references("Token.id"),
    tokenOut: p.one("tokenOutId"),
    tokenAmountOut: p.bigint(),
    appData: p.bytes(),
    to: p.bytes(),
    isSellOrder: p.boolean(),
    isPartiallyFillable: p.boolean(),
    validityBucketSeconds: p.bigint(),
    sellTokenPriceOracle: p.bytes(),
    buyTokenPriceOracle: p.bytes(),
    strike: p.bigint(),
    maxTimeSinceLastOracleUpdate: p.bigint(),
    blockNumber: p.bigint(),
    blockTimestamp: p.bigint(),
    orderContract: p.bytes(),
    user: p.string().references("User.id"),
  }),
  Token: p.createTable({
    id: p.string(),
    address: p.bytes(),
    chainId: p.int(),
    name: p.string(),
    symbol: p.string(),
    decimals: p.int(),
  }),
  User: p.createTable({
    id: p.string(),
    address: p.string(),
    chainId: p.int(),
    orders: p.many("Order.user"),
  }),
}));
