export const cowAmmModuleAbi = [
  {
    inputs: [
      { internalType: "address", name: "_settler", type: "address" },
      {
        internalType: "address",
        name: "_extensibleFallbackHandler",
        type: "address",
      },
      { internalType: "address", name: "_composableCow", type: "address" },
      { internalType: "address", name: "_handler", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "ActiveAMM", type: "error" },
  { inputs: [], name: "NoActiveAMM", type: "error" },
  { inputs: [], name: "TokenBalanceZero", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract Safe",
        name: "safe",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "orderHash",
        type: "bytes32",
      },
    ],
    name: "CowAmmClosed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract Safe",
        name: "safe",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IERC20",
        name: "token0",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IERC20",
        name: "token1",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "orderHash",
        type: "bytes32",
      },
    ],
    name: "CowAmmCreated",
    type: "event",
  },
  {
    inputs: [],
    name: "COMPOSABLE_COW",
    outputs: [
      { internalType: "contract ComposableCoW", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "COW_DOMAIN_SEPARATOR",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "EXTENSIBLE_FALLBACK_HANDLER",
    outputs: [
      {
        internalType: "contract ExtensibleFallbackHandler",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "HANDLER",
    outputs: [
      { internalType: "contract IConditionalOrder", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SETTLER",
    outputs: [
      { internalType: "contract GPv2Settlement", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "VAULT_RELAYER",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "contract Safe", name: "", type: "address" }],
    name: "activeOrders",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "closeAmm",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "contract IERC20", name: "token0", type: "address" },
      { internalType: "contract IERC20", name: "token1", type: "address" },
      { internalType: "uint256", name: "minTradedToken0", type: "uint256" },
      { internalType: "address", name: "priceOracle", type: "address" },
      { internalType: "bytes", name: "priceOracleData", type: "bytes" },
      { internalType: "bytes32", name: "appData", type: "bytes32" },
    ],
    name: "createAmm",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "contract IERC20", name: "token0", type: "address" },
      { internalType: "contract IERC20", name: "token1", type: "address" },
      { internalType: "uint256", name: "minTradedToken0", type: "uint256" },
      { internalType: "address", name: "priceOracle", type: "address" },
      { internalType: "bytes", name: "priceOracleData", type: "bytes" },
      { internalType: "bytes32", name: "appData", type: "bytes32" },
    ],
    name: "replaceAmm",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
