export const apiChainNameToNetworkNumber = {
  MAINNET: 1,
  POLYGON: 137,
  GOERLI: 5,
  ARBITRUM: 42161,
  GNOSIS: 100,
  BASE: 8453,
  AVALANCHE: 43114,
  ZKSYNC: 0,
  ZKEVM: 1_101,
  FANTOM: 0,
  OPTIMISM: 10,
  SEPOLIA: 11155111,
  "%future added value": 0,
};

export const apiChainNameToGaugeType = {
  MAINNET: "Ethereum",
  POLYGON: "Polygon",
  GOERLI: "Goerli",
  ARBITRUM: "Arbitrum",
  GNOSIS: "Gnosis",
  BASE: "Base",
  AVALANCHE: "Avalanche",
  ZKSYNC: "ZKsync",
  ZKEVM: "PolygonZkEvm",
  FANTOM: "Fanton",
  OPTIMISM: "Optimism",
  SEPOLIA: "Sepolia",
  "%future added value": "Ethereum",
};
